default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: user_service_api_development

test:
  <<: *default
  database: user_service_api_test

production:
  <<: *default
  database: user_service_api
